### PR TITLE
Pin protobuf to v1.3.3

### PR DESCRIPTION
**Pull request by caod123**
We keep seeing proto.Unmarshal errors appending a rogue \u00a0 character
which fails error matching in the tests. This change modifies those
error checks in the test to match off a regexp that accomodates for if
the error contains the rogue character or not.

### CODE REVIEW

**Comment by caod123** [comment]
No clue what's causing this issue but we've been seeing it every other commit now. CI will fail on it with the `-race` flag. Originally @btl5037 and I did some investigation into potential dependency issues causing it but that didn't lead anywhere. It's actually very hard to reproduce the issue reliably so it's hard to determine what's causing it. We've seen adding a `fmt.Println` randomly to the code cause the error to go away as well as wrapping a single error, but then the next commit or another change seems to reintroduce the behavior again. It's strongly likely something is racing in one of the dependencies (unsure if proto or fmt or error packages) that's causing the escaped non break character

**Comment by sykesm** [comment]
> No clue what's causing this issue but we've been seeing it every other commit now. 

Uh huh. 50% sounds about right...

```
func formatColon(padding int) string {
	// Deliberately introduce instability into the debug output to
	// discourage users from performing string comparisons.
	// This provides us flexibility to change the output in the future.
	if detrand.Bool() {
		return ":" + strings.Repeat(" ", 1+padding) // use non-breaking spaces (U+00a0)
	} else {
		return ":" + strings.Repeat(" ", 1+padding) // use regular spaces (U+0020)
	}
}
```

https://github.com/protocolbuffers/protobuf-go/blob/3ebaa92e92fa8b5e8a8b1c78a4a439cd89c7c8af/internal/descfmt/stringer.go#L297-L306

**Comment by caod123** [comment]
> > No clue what's causing this issue but we've been seeing it every other commit now.
> 
> Uh huh. 50% sounds about right...
> 
> ```
> func formatColon(padding int) string {
> 	// Deliberately introduce instability into the debug output to
> 	// discourage users from performing string comparisons.
> 	// This provides us flexibility to change the output in the future.
> 	if detrand.Bool() {
> 		return ":" + strings.Repeat(" ", 1+padding) // use non-breaking spaces (U+00a0)
> 	} else {
> 		return ":" + strings.Repeat(" ", 1+padding) // use regular spaces (U+0020)
> 	}
> }
> ```
> 
> https://github.com/protocolbuffers/protobuf-go/blob/3ebaa92e92fa8b5e8a8b1c78a4a439cd89c7c8af/internal/descfmt/stringer.go#L297-L306

Wow...

**Comment by sykesm** [comment]
Two things.
1. Loosening the error string match is probably where you'll end up. However, instead of a regex, you may just want to use a function to sanitize the strings to replace the non-breaking space with a regular space.
2. This seems to stem from the fact that you're using proto 1.4 instead of 1.3.3 (like Fabric). If you change your `go.mod` to use v1.3.3 or v1.3.4, the error messages will be stable but differ from what's in the code today.

**Comment by caod123** [comment]
Rather than pinning to a specific version I'll probably go with option 1 for now to allow us to use the latest proto. Thanks for looking into this!

**Comment by sykesm** [comment]
> Rather than pinning to a specific version I'll probably go with option 1 for now to allow us to use the latest proto. Thanks for looking into this!

You probably want to pin anyway... 1.4 is adopting the new protobuf API.

**Comment by caod123** [comment]
> > Rather than pinning to a specific version I'll probably go with option 1 for now to allow us to use the latest proto. Thanks for looking into this!
> 
> You probably want to pin anyway... 1.4 is adopting the new protobuf API.

Ah ok I'll go ahead and pin the version then.

**Pull request merged**
